# TODO: i18 Support

fonts_api:
  google: https://fonts.googleapis.com/css?family=
  active: google

menu:
  getting-started:
    label: 开始使用
    href: /getting-started.html
  theme-settings:
    label: RPC配置
    href: /theme-settings.html
  advanced-settings:
    label: 高级设置
    href: /advanced-settings.html
  third-party-services:
    label: 插件扩展
    href: /third-party-services.html
  faqs:
    label: 常见问题
    href: /faqs.html
  platforms:
    label: 参与贡献
    href: /platforms.html


